# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kav < Formula
  desc "Kubernetes auth Akeyless Validator"
  homepage ""
  version "1.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.2/k8s-auth-validator_Darwin_arm64.tar.gz"
      sha256 "1608d12664b7fe61d136e7275ccb173341479dce265c7436674a986341c25f32"

      def install
        bin.install "k8s-auth-validator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.2/k8s-auth-validator_Darwin_x86_64.tar.gz"
      sha256 "0410c5595430e5c8d41ab8442cd7617106278b553fb4f3701cf8ba7638b1ebd7"

      def install
        bin.install "k8s-auth-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.2/k8s-auth-validator_Linux_x86_64.tar.gz"
      sha256 "6d7c0a454c86d4aaa4356056a1b4049a83f09b209c4ee3bea46ebad42b2109f5"

      def install
        bin.install "k8s-auth-validator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.2/k8s-auth-validator_Linux_arm64.tar.gz"
      sha256 "318dc43c38451bcf6311e36589801eca361406bc65f6c78d7ed40b8512ab0e2b"

      def install
        bin.install "k8s-auth-validator"
      end
    end
  end
end
