# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kav < Formula
  desc "Kubernetes auth Akeyless Validator"
  homepage "https://github.com/akeyless-community/k8s-auth-validator"
  version "1.2.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.5/k8s-auth-validator_Darwin_arm64.tar.gz"
      sha256 "82ced8af4a3816aebcfc8ce7d75665fd37f869e20a27142b4116c0a7f11a1930"

      def install
        bin.install "k8s-auth-validator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.5/k8s-auth-validator_Darwin_x86_64.tar.gz"
      sha256 "277eb144aa481b2c2987ab2dc138e81b40e175f7df0288cf825526e6ba16eabc"

      def install
        bin.install "k8s-auth-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.5/k8s-auth-validator_Linux_arm64.tar.gz"
      sha256 "1d04ecbd8159c146a9037abf81fab05ab6eb1b8ac495fa56e930109e9eaa73db"

      def install
        bin.install "k8s-auth-validator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akeyless-community/k8s-auth-validator/releases/download/1.2.5/k8s-auth-validator_Linux_x86_64.tar.gz"
      sha256 "4b8ff3af0ff60c1245f29ec2c7785f3cd5a47c86ab573267e3ad7d55fa65c8c6"

      def install
        bin.install "k8s-auth-validator"
      end
    end
  end
end
